// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type ContentsType = {
  id:       any;
  title:    string;
  img:      string;
}

