// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type PagesType = {
  code:    any
  message: string
  results: PagesResultsType
}

export type PagesResultsType = {
  id:       any;
  book:     number;
  number:   number;
}