// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type BooksType = {
  code:     number;
  message:  string;
  results:  BooksResultsType;
}

export type BooksResultsType = {
  id:           any;
  title:        string;
  category:     string;
  image_cover:  string;
}