// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export type BooksType = {
  code:    any
  message: string
  results: BooksResultsType
}

export type BooksResultsType = {
  results: any
  id:       any;
  title:    string;
  img:      string;
}